### ISSUE TITLE
Hardcoded

### ISSUE THREAD

**Issue by dinism** [ndunand/moodle-atto_morefontcolors#17]
Thanks a lot for the plugin.
I'm a PT-PT translator.
Can this string be translated? THANKS
![imagem](https://user-images.githubusercontent.com/14828021/119665741-97d3a300-be2c-11eb-8fa1-b7621582ce31.png)

**Comment by ndunand** [comment]
@dinism thanks for the report. This string comes from the YUI library, and there seems to not be any solution to provide localization to this string using the plugin or AMOS.

For reference, the localizations for this particular YUI component are in `lib/yuilib/3.17.2/dial/lang`.

My fix, as this label should not be displayed anyway, is to not display it. This will be fixed in the next release.
