### ISSUE TITLE
Upgrade for 4.0

### ISSUE THREAD

**Issue by a-lunario** [ndunand/moodle-atto_morefontcolors#19]
addition of colours into the drop grid and custom colour picker does not work in the current moodle 4.0

**Comment by julien-garrigue** [comment]
Please ugrade for 4.1
As soon as I upgraded to 4.1 the plugin disappeared and deactivated from my plugin list.
I can't install it from Moodle pluging website under the 4.1 version : https://moodle.org/plugins/?q=certificate%20moodle-version:4.1

**Comment by NicoAlexH** [comment]
@a-lunario I'm currently testing the plugin on Moodle 4.1 (LTS version), it seems to be working ; could you check if you still have this issue ? 
(Don't forget to add the string `morefontcolors` in the Atto toolbar settings, in order to enable the color picker).

@julien-garrigue We will update the plugin compatibility to 4.1 in the next few days, as soon as we're finished with testing.
